// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PatioVision.Data.Context;

#nullable disable

namespace PatioVision.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatioVision.Core.Models.DispositivoIoT", b =>
                {
                    b.Property<Guid>("DispositivoIotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UltimaLocalizacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("DispositivoIotId");

                    b.ToTable("DISPOSITIVO_IOT", (string)null);
                });

            modelBuilder.Entity("PatioVision.Core.Models.Moto", b =>
                {
                    b.Property<Guid>("MotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("DispositivoIotId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid>("PatioId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MotoId");

                    b.HasIndex("DispositivoIotId");

                    b.HasIndex("PatioId");

                    b.ToTable("MOTO", (string)null);
                });

            modelBuilder.Entity("PatioVision.Core.Models.Patio", b =>
                {
                    b.Property<Guid>("PatioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("DispositivoIotId")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("PatioId");

                    b.HasIndex("DispositivoIotId");

                    b.ToTable("PATIO", (string)null);
                });

            modelBuilder.Entity("PatioVision.Core.Models.Moto", b =>
                {
                    b.HasOne("PatioVision.Core.Models.DispositivoIoT", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoIotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatioVision.Core.Models.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("PatioVision.Core.Models.Patio", b =>
                {
                    b.HasOne("PatioVision.Core.Models.DispositivoIoT", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoIotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("PatioVision.Core.Models.Patio", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
